name: pubnub_flutter
description: Flutter extensions for PubNub Dart SDK
version: 1.0.0
homepage: https://www.pubnub.com/docs/platform/home

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

scripts:
  test:
    default: flutter test
  validate:
    analysis: flutter analyze
    formatting: flutter format -n --set-exit-if-changed lib

dependencies:
  async: ^2.4.2
  pubnub: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter