name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    env:
      FLUTTER_PATH: "/tmp/flutter"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Dart stable
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: "Build and run tests for 'pubnub'"
        env:
          PKG: pubnub
        run: |
          sudo -E apt-get -yq --no-install-suggests install lib32stdc++6
          pub global activate derry 1.3.0
          cd "${{ github.workspace }}/pubnub"
          pub get
          derry validate analysis
          derry validate formatting
          derry test default
      - name: "Build and run tests for 'pubnub_flutter'"
        env:
          PKG: pubnub_flutter
          FLUTTER: true
        run: |
          sudo -E apt-get -yq --no-install-suggests install lib32stdc++6
          git clone https://github.com/flutter/flutter.git -b stable "$FLUTTER_PATH"
          export PATH="$PATH:$FLUTTER_PATH/bin"
          pub global activate derry 1.3.0
          cd "${{ github.workspace }}/pubnub_flutter"
          flutter pub get
          derry validate analysis
          derry validate formatting
          derry test default
  acceptance:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Run acceptance tests
        run: |
          cd acceptance_tests
          dart pub get
          export FEATURES_PATH=../sdk-specifications/features
          dart pub run acceptance_tests
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        with:
          name: acceptance-test-reports
          path: acceptance_tests/report.xml
